# .goreleaser.yml
# Build customization
project_name: mmock
builds:
  - main: cmd/mmock/main.go
    binary: mmock
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.VERSION={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
dockers:
  - 
    dockerfile: Dockerfile
    skip_push: false
    image_templates:
      - "jordimartin/mmock:{{.Tag}}"
      - "jordimartin/mmock:latest"
    extra_files:
      - tls/server.crt
      - tls/server.key
release:
  github:
    owner: jmartin82
    name: mmock
  draft: false
changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - rollback
env_files:
  github_token: .github