# .goreleaser.yml
# Build customization
builds:
  - main: cmd/mmock/main.go
    binary: mmock
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.VERSION={{.Version}}
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - README.md
    - config/*
    - tls/*
dockers:
  - 
    dockerfile: Dockerfile
    skip_push: false
    binary: mmock
    image_templates:
      - "jordimartin/mmock:{{.Tag}}"
      - "jordimartin/mmock:latest"
    extra_files:
      - tls/server.crt
      - tls/server.key
release:
  github:
    owner: jmartin82
    name: mmock
  draft: false
changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - rollback
env_files:
  github_token: .github