language: go
go: 
  - 1.6
  - 1.7.x

install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/go/bin
  - export PATH="${TRAVIS_BUILD_DIR}/go/bin:$PATH"
  - mkdir -p ${TRAVIS_BUILD_DIR}/go
  - export GOPATH="${TRAVIS_BUILD_DIR}/go:$GOPATH"
  - make get-deps

script:
  - make test