--- # First request
description: Returns 'Hello world!'
request:
  method: GET
  path: /multi_request_1
response:
  statusCode: 200
  body: >
    Hello request 1!
--- # Second request
description: Returns 'Boom!'
request:
  method: GET
  path: /multi_request_2
response:
  statusCode: 200
  body: >
    Boom request 2!